// 単純なシェーダ.

struct VertexIn
{
  float4 position	: POSITION;
  float4 color : COLOR;
  float2 texcoord : TEXCOORD0;
};

struct VertexOut
{
  float4 position	: POSITION;
  float4 color : COLOR;
  float2 texcoord : TEXCOORD0;
};

VertexOut tex_simple_v_main(in VertexIn input, uniform float4x4 modelViewProj)
{
  VertexOut output;
  output.position =	mul(modelViewProj, input.position);
  output.color = input.color;
  output.texcoord = input.texcoord;
  return output;
}
